POST http://localhost:8080/user
Authorization: Basic YWxiZToxMjM=
Content-Type: application/json
User-Agent: Mozilla/5.0

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "securePassword123",
  "image": "https://example.com/profile.jpg",
  "isTwofactorEnabled": true
}